# Generated by Django 6.0.3 on 2026-04-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('perceived_intensity', models.PositiveIntegerField(blank=True, help_text='1-10 RPE scale', null=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_rounds', models.PositiveIntegerField(blank=True, null=True)),
                ('work_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='exercises.exercise')),
            ],
        ),
    ]
