# Generated by Django 6.0.3 on 2026-04-01 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followrelation',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followrelation',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerrelation',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerrelation',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='followrelation',
            unique_together={('follower', 'followed_user')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerrelation',
            unique_together={('requester', 'addressee')},
        ),
    ]
