# Generated by Django 6.0.3 on 2026-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('location_text', models.CharField(blank=True, max_length=200)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('weekly_availability', models.PositiveIntegerField(default=3, help_text='Number of training days per week')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_equipment', models.ManyToManyField(blank=True, related_name='available_to', to='taxonomy.equipment')),
                ('body_focus_preferences', models.ManyToManyField(blank=True, related_name='preferred_by', to='taxonomy.bodypart')),
                ('preferred_styles', models.ManyToManyField(blank=True, related_name='preferred_by', to='taxonomy.martialstyle')),
            ],
        ),
    ]
