# Generated by Django 6.0.3 on 2026-04-01 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('taxonomy', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='primary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans', to='taxonomy.martialstyle'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='training_plans', to='taxonomy.tag'),
        ),
        migrations.AddField(
            model_name='trainingplanday',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_days', to='workouts.workout'),
        ),
        migrations.AddField(
            model_name='trainingplanweek',
            name='training_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='plans.trainingplan'),
        ),
        migrations.AddField(
            model_name='trainingplanday',
            name='training_plan_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='plans.trainingplanweek'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingplanweek',
            unique_together={('training_plan', 'week_number')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingplanday',
            unique_together={('training_plan_week', 'day_number')},
        ),
    ]
