# Generated by Django 6.0.3 on 2026-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('full_description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('common_mistakes', models.TextField(blank=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('duration_hint_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_parts', models.ManyToManyField(blank=True, related_name='exercises', to='taxonomy.bodypart')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
