# Generated by Django 6.0.3 on 2026-04-01 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_required',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='taxonomy.equipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='taxonomy.martialstyle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='taxonomy.tag'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_types',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='taxonomy.workouttype'),
        ),
    ]
