# Generated by Django 6.0.3 on 2026-04-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
        ('taxonomy', '0005_musclegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='taxonomy.musclegroup'),
        ),
    ]
