# Generated by Django 6.0.3 on 2026-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('workout', 'Workout'), ('plan_day', 'Plan Day'), ('custom_training', 'Custom Training'), ('partner_session', 'Partner Session'), ('rest_day', 'Rest Day')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled')], default='planned', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('followers', 'Followers'), ('invited', 'Invited Only'), ('public', 'Public')], default='private', max_length=20)),
                ('location_text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventInviteResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
