# Generated by Django 6.0.3 on 2026-04-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('gif', 'GIF'), ('image', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to='exercises/media/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exercises/thumbnails/%Y/%m/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='exercises.exercise')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
