# Generated by Django 6.0.3 on 2026-04-01 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('followers', 'Followers'), ('public', 'Public')], default='private', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_parts', models.ManyToManyField(blank=True, related_name='workouts', to='taxonomy.bodypart')),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_workouts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
                ('equipment_used', models.ManyToManyField(blank=True, related_name='workouts', to='taxonomy.equipment')),
                ('primary_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='taxonomy.martialstyle')),
                ('tags', models.ManyToManyField(blank=True, related_name='workouts', to='taxonomy.tag')),
                ('workout_types', models.ManyToManyField(blank=True, related_name='workouts', to='taxonomy.workouttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('warmup', 'Warmup'), ('technique', 'Technique'), ('rounds', 'Rounds'), ('conditioning', 'Conditioning'), ('cooldown', 'Cooldown')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workouts.workout')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('rounds', models.PositiveIntegerField(blank=True, null=True)),
                ('work_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='exercises.exercise')),
                ('workout_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutblock')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
