# Generated by Django 6.0.3 on 2026-04-02 11:10

from django.db import migrations, models


def migrate_block_types(apps, schema_editor):
    """Map old block types to new simplified types"""
    WorkoutBlock = apps.get_model('workouts', 'WorkoutBlock')
    
    # Map old types to new types
    type_mapping = {
        'technique': 'training',
        'rounds': 'training',
        'conditioning': 'training',
    }
    
    for old_type, new_type in type_mapping.items():
        WorkoutBlock.objects.filter(block_type=old_type).update(block_type=new_type)


def reverse_migrate(apps, schema_editor):
    """Reverse migration - keep as training"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutblock',
            name='block_type',
            field=models.CharField(choices=[('warmup', 'Warmup'), ('training', 'Training'), ('cooldown', 'Cooldown'), ('rest', 'Rest')], max_length=20),
        ),
        migrations.RunPython(migrate_block_types, reverse_migrate),
    ]
