# Generated by Django 6.0.3 on 2026-04-01 15:17

from django.db import migrations


BODY_PARTS = [
    # Canonical body parts matching SVG body map data
    ("Adductors", "adductors"),
    ("Ankles", "ankles"),
    ("Biceps", "biceps"),
    ("Calves", "calves"),
    ("Chest", "chest"),
    ("Feet", "feet"),
    ("Forearm", "forearm"),
    ("Front Deltoids", "front-deltoids"),
    ("Gluteal", "gluteal"),
    ("Hamstring", "hamstring"),
    ("Hands", "hands"),
    ("Head", "head"),
    ("Knees", "knees"),
    ("Lower Abs", "lower-abs"),
    ("Lower Back", "lower-back"),
    ("Middle Abs", "middle-abs"),
    ("Neck", "neck"),
    ("Obliques", "obliques"),
    ("Quadriceps", "quadriceps"),
    ("Rear Deltoids", "rear-deltoids"),
    ("Tibialis", "tibialis"),
    ("Trapezius", "trapezius"),
    ("Triceps", "triceps"),
    ("Upper Abs", "upper-abs"),
    ("Upper Back", "upper-back"),
]


def seed_body_parts(apps, schema_editor):
    BodyPart = apps.get_model("taxonomy", "BodyPart")
    for name, slug in BODY_PARTS:
        BodyPart.objects.get_or_create(slug=slug, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_body_parts, migrations.RunPython.noop),
    ]
